apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  namespace: flo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: landing-page
          image: floreagabriel/ggdevs_landin_page:v1 
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: landing-page-svc
  namespace: flo
spec:
  type: ClusterIP
  selector:
    app: landing-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-app-ingress
  namespace: flo
spec:
  rules:
    - host: home.ggdevs.site 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-page-svc
                port:
                  number: 80

